Repository JeanAEckelberg/byte_engine, pull requests merged in 2024-01, with the labels that each got.

#129 94 improve exception strings
  game/common/avatar.py
  game/common/items/item.py
  game/common/map/game_board.py
  game/common/map/occupiable.py
  game/common/map/tile.py
  game/common/player.py
  game/common/stations/occupiable_station.py
  game/test_suite/tests/test_avatar.py
  game/test_suite/tests/test_avatar_inventory.py
  game/test_suite/tests/test_game_board_no_gen.py
  game/test_suite/tests/test_item.py
  game/test_suite/tests/test_occupiable_station.py
  game/test_suite/tests/test_player.py
  game/test_suite/tests/test_station.py
Labels: enhancement

#144 Added config documentation
  visualizer/__init__.py
  visualizer/adapter.py
  visualizer/bytesprites/__init__.py
  visualizer/config.py
  visualizer/templates/__init__.py
Labels: documentation

#147 Added documentation to the main file of visualizer
  visualizer/main.py
  visualizer/utils/log_reader.py
Labels: documentation

#146 Added documenation to the spritesheet class
  visualizer/utils/spritesheet.py
Labels: documentation

#145 Added documentation to the Adapter
  visualizer/adapter.py
Labels: documentation

#149 Updated Vector to reduce side effects
  game/controllers/movement_controller.py
  game/engine.py
  game/utils/validation.py
  game/utils/vector.py
  visualizer/adapter.py
  visualizer/templates/menu_templates.py
  visualizer/templates/playback_template.py
Labels: Engine, Byte Framework
